version: "3.9"

services:
  db:
    image: postgres:16
    container_name: finman_db
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/finman_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      dockerfile: dockerfile
    container_name: finman_backend
    ports:
      - "28000:28000"
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
       - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
       - ASPNETCORE_URLS=http://0.0.0.0:28000
    depends_on:
      db:
        condition: service_healthy
        # to entrypoint wait-for-sql.sh && 
    entrypoint: ["/bin/sh", "-c", "dotnet Finance_Manager_Backend.dll"]