FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore --verbosity detailed

COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
# Add wait-for-sql.sh to /app
COPY wait-for-sql.sh .
RUN chmod +x wait-for-sql.sh

EXPOSE 28000

ENTRYPOINT [ "dotnet", "Finance_Manager_Backend.dll" ]
